### PR TITLE
GH-3350 - Updating language for linking modals

### LINKED ISSUE #3350: Bug: "Link Board" button is red and capitalization is incorrect
## Steps to reproduce the behavior

1. Open Boards app bar in Channels
2. Add a channel to link
3. See the confirmation modal
4. The "Yes, link board" button is red, which usually indicates a destructive action.

## Expected behavior

The "Yes, link board" button should be dark blue, the the words "link board" should be capitalized. The words in modal title should also be capitalized as well. See designs. cc @asaadmahmood 

### Actual
Screen Shot 2022-07-11 at 11 27 02 AM
### Designs
image

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 (bug bash)
 - Browser and OS: Chrome on Mac

### LINKED ISSUE #3512: Bug: Lack of margin between text and button in link dialog
## Steps to reproduce the behavior

1. Select Boards icon from channel header and select + Add
2. Notice that long descriptions go up to the button

## Expected behavior

There should be a margin between text and the button

## Screenshots (optional)

Screen Shot 2022-08-01 at 3 09 24 PM

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bugbash
 - Browser and OS: Chrome on Mac

### LINKED ISSUE #3523: Bug: Not obvious you can search for a channel in the Share dialog
## Steps to reproduce the behavior

1. Open the Share dialog for a board
2. Not obvious how to link to a channel

## Expected behavior

Recommend changing the search box placeholder text to "Search for people or channels"

## Screenshots (optional)

Screen Shot 2022-08-02 at 2 56 50 PM

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 bugbash
 - Browser and OS: Chrome on Mac

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
GH-3350 - Updating language for linking modals and the color of buttons
GH-3512 - Added margin between button and text in link modal
GH-3523 - Updated text in share modal

#### Ticket Link
Fixes #3350
Fixes #3512
Fixes #3523

#### Screenshots
Screenshot 2022-08-02 at 6 18 28 PM
Screenshot 2022-08-02 at 6 18 57 PM
Screenshot 2022-08-02 at 6 19 12 PM
Screenshot 2022-08-02 at 6 19 22 PM

### CODE REVIEW

File: mattermost-plugin/webapp/src/components/boardSelector.tsx [hunk 1]
```diff
@@ -116,12 +116,12 @@ const BoardSelector = () => {
     if (showLinkBoardConfirmation?.channelId !== '') {
         confirmationSubText = intl.formatMessage({
             id: 'boardSelector.confirm-link-board-subtext-with-other-channel',
-            defaultMessage: 'Linking the "{boardName}" board to this channel would give all members of this channel "Editor" access to the board.\n\nAdditionally, this board is linked to another channel, and will be unlinked from the other channel when you link it here.\n\nAre you sure you want to link it?'
-        }, {boardName: showLinkBoardConfirmation?.title})
+            defaultMessage: 'Linking the "{boardName}" board to this channel would give all members of this channel "Editor" access to the board.{lineBreak} Additionally, this board is linked to another channel, and will be unlinked from the other channel when you link it here.'
```
Comment (justinegeffen) [inline mattermost-plugin/webapp/src/components/boardSelector.tsx:119]:
```suggestion
            defaultMessage: 'When you link "{boardName}" to the channel, all members of the channel (existing and new) will be able to edit it.{lineBreak} This board is currently linked to another channel. It will be unlinked if you choose to link it here.'
```

File: webapp/i18n/en.json [hunk 2]
```diff
@@ -360,14 +360,13 @@
...
-  "shareBoard.confirm-unlink.body": "When you unlink a channel from a board, all members of the channel (existing and new) will loose access to it unless they are given permission separately. {lineBreak} Are you sure you want to unlink it?",
-  "shareBoard.confirm-unlink.confirmBtnText": "Yes, unlink",
+  "shareBoard.confirm-link-channel-button": "Link channel",
+  "shareBoard.confirm-link-channel-button-with-other-channel": "Unlink and link here",
+  "shareBoard.confirm-link-channel-subtext": "When you link a channel to a board, all members of the channel (existing and new) will be able to edit it.",
+  "shareBoard.confirm-link-channel-subtext-with-other-channel": "When you link a channel to a board, all members of the channel (existing and new) will be able to edit it.{lineBreak}This board is currently linked to another channel. It will be unlinked if you choose to link it here.",
   "shareBoard.confirm-unlink.title": "Unlink channel from board",
+  "shareBoard.confirm-unlink.body": "When you unlink a channel from a board, all members of the channel (existing and new) will lose access to it unless they are given permission separately.",
```
Comment (justinegeffen) [inline webapp/i18n/en.json:368]:
```suggestion
  "shareBoard.confirm-unlink.body": "When you unlink a channel from a board, all members of the channel (existing and new) will lose access to it unless they're given permission separately.",
```

File: webapp/i18n/en_AU.json [hunk 3]
```diff
@@ -305,8 +305,8 @@
   "WelcomePage.NoThanks.Text": "No thanks, I'll figure it out myself",
   "Workspace.editing-board-template": "You're editing a board template.",
   "boardSelector.confirm-link-board": "Link board to channel",
-  "boardSelector.confirm-link-board-button": "Yes, link board",
-  "boardSelector.confirm-link-board-subtext": "Linking the '\\{boardName}'\\ board to this channel would give all members of this channel 'Editor' access to the board. Are you sure you want to link it?",
+  "boardSelector.confirm-link-board-button": "Link board",
+  "boardSelector.confirm-link-board-subtext-with-other-channel": "Linking the \"{boardName}\" board to this channel would give all members of this channel \"Editor\" access to the board.{lineBreak} Additionally, this board is linked to another channel, and will be unlinked from the other channel when you link it here.",
```
Comment (justinegeffen) [inline webapp/i18n/en_AU.json:309]:
```suggestion
  "boardSelector.confirm-link-board-subtext-with-other-channel": "When you link "{boardName}" to the channel, all members of the channel (existing and new) will be able to edit it.{lineBreak} This board is currently linked to another channel. It will be unlinked if you choose to link it here.",
```

File: webapp/src/components/shareBoard/channelPermissionsRow.tsx [hunk 4]
```diff
@@ -58,13 +58,11 @@ const ChannelPermissionsRow = (): JSX.Element => {
                 }),
                 subText: intl.formatMessage({
                     id: 'shareBoard.confirm-unlink.body',
-                    defaultMessage: 'When you unlink a channel from a board, all members of the channel (existing and new) will loose access to it unless they are given permission separately. {lineBreak} Are you sure you want to unlink it?',
-                }, {
-                    lineBreak: <p/>
+                    defaultMessage: 'When you unlink a channel from a board, all members of the channel (existing and new) will lose access to it unless they are given permission separately.',
```
Comment (justinegeffen) [inline webapp/src/components/shareBoard/channelPermissionsRow.tsx:61]:
```suggestion
                    defaultMessage: 'When you unlink a channel from a board, all members of the channel (existing and new) will lose access to it unless they're given permission separately.',
```

File: webapp/i18n/en.json [hunk 5]
```diff
@@ -305,9 +305,9 @@
...
-  "boardSelector.confirm-link-board-subtext": "Linking the \"{boardName}\" board to this channel would give all members of this channel \"Editor\" access to the board. Are you sure you want to link it?",
-  "boardSelector.confirm-link-board-subtext-with-other-channel": "Linking the \"{boardName}\" board to this channel would give all members of this channel \"Editor\" access to the board. Additionally, this board is linked to another channel, and will be unlinked from the other channel when you link it here. Are you sure you want to link it?",
+  "boardSelector.confirm-link-board-button": "Link board",
+  "boardSelector.confirm-link-board-subtext": "When you link \"{boardName}\" to the channel, all members of the channel (existing and new) will be able to edit it. You can unlink a board from a channel at any time.",
+  "boardSelector.confirm-link-board-subtext-with-other-channel": "Linking the \"{boardName}\" board to this channel would give all members of this channel \"Editor\" access to the board.{lineBreak} Additionally, this board is linked to another channel, and will be unlinked from the other channel when you link it here.",
```
Comment (justinegeffen) [inline webapp/i18n/en.json:310]:
```suggestion
  "boardSelector.confirm-link-board-subtext-with-other-channel": "When you link a channel to a board, all members of the channel (existing and new) will be able to edit it.{lineBreak}This board is currently linked to another channel. It will be unlinked if you choose to link it here.",
```

**Review by justinegeffen — COMMENTED** [review]
Copy changes for consistency and two minor updates. Looks like everything is consistent now.

**Review by harshilsharma63 — APPROVED** [review]
