### PR TITLE
[GH-1007] Fix popup menus visibility

### LINKED ISSUE #1007: Bug: popup menu disappears when mouse is not over
**Summary:**
Some components contain a button that appears only on hover and allows to show popup menu. Such popup menus disappear when the mouse is moved away and reappear when mouse is over the component.

**Expected behavior:**
Popup menu should be visible until user clicks somewhere.

**Screenshots:**
Kanban card:
PopupMenuKanbanCard

Gallery card:
PopupMenuGalleryCard

Card comment:
PopupMenuComment

Card description:
PopupMenuCardDescription

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

### PR DESCRIPTION
**Pull request by kamre**
#### Summary
Always show popup menu when it is opened:
- applied to popup menus for cards in kanban/gallery/calendar, menus for content block and comment
- add additional class name `menuOpened` and ensure that menu is visible
- new component `CardActionsMenuIcon` introduced and used for kanban/gallery/calendar card actions menu
- increase `z-index` for `ContentBlock` when menu is opened to avoid overlaps
- jest snapshots updated: additional classes added to existing elements

#### Ticket Link
Fixed #1007

### CODE REVIEW

File: webapp/src/components/contentBlock.tsx [hunk 1]
```diff
@@ -94,6 +99,7 @@ const ContentBlock = (props: Props): JSX.Element => {
                                 id='insertAbove'
                                 name={intl.formatMessage({id: 'ContentBlock.insertAbove', defaultMessage: 'Insert above'})}
                                 icon={<AddIcon/>}
+                                position='top'
```
Comment (kamre) [inline webapp/src/components/contentBlock.tsx:102]: @asaadmahmood @wuwinson this shows submenu like this:
image
and helps to avoid increasing scroll height of the card dialog.

What do you think about such change?

**Review by asaadmahmood — APPROVED** [review]

**Review by wuwinson — APPROVED** [review]
LGTM!

**Review by sbishel — APPROVED** [review]

**Comment by kamre** [comment]
@sbishel I have updated jest snapshot for `mattermost-plugin` test

**Comment by jordanafung** [comment]
Hi @kamre 
You were selected as one of our Top Contributors for Hacktoberfest!
Please fill out [this form](https://docs.google.com/forms/d/11pLB3pF1CmOslYqHr7c7bxFWU6QAEAJuiaKgHD1vJtg) to select your swag as thanks!
Thank you for all you do and for making Mattermost even better!
