### PR TITLE
Opened markdown links in new tab

### LINKED ISSUE #753: Bug: Clicking on a Markdown link should open it in a new tab
**Steps to reproduce the behavior:**
1. Open a card with a link in the Markdown description (or add one)
2. Click on the link
3. The card enters edit mode, then the link is opened in the same tab

**Expected behavior:**
The link should open in a new (_blank) tab, without entering edit mode.

**Screenshots:**
https://user-images.githubusercontent.com/46905241/126238307-fc2b1fb8-d573-4b43-b1af-dc2e70b4222b.mov

**Platform:**
 - Focalboard plugin 0.8.1 on community server, Chrome 91 on macOS

**Additional context:**
This is a regression.

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Opened markdown links in new tab

#### Ticket Link
Fixes #753

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]

File: webapp/src/utils.ts [hunk 1]
```diff
@@ -112,8 +112,14 @@ class Utils {
...
         const renderer = new marked.Renderer()
-        if ((window as any).openInNewBrowser) {
-            renderer.link = (href, title, contents) => `<a target="_blank" rel="noreferrer" href="${encodeURI(href || '')}" title="${title ? encodeURI(title) : ''}" onclick="event.stopPropagation(); openInNewBrowser && openInNewBrowser(event.target.href);">${contents}</a>`
+        renderer.link = (href, title, contents) => {
+            return '<a ' +
+                'target="_blank" ' +
+                'rel="noreferrer" ' +
+                `href="${encodeURI(href || '')}" ` +
+                `title="${title ? encodeURI(title) : ''}" ` +
+                'onclick="event.stopPropagation(); openInNewBrowser && openInNewBrowser(event.target.href);"' +
```
Comment (hahmadia) [inline webapp/src/utils.ts:121]: Nice change :)

Comment (jespino) [reply webapp/src/utils.ts:121]: this `openInNewBrowser` was something for the desktop app, and allowing this everywhere is not needed, and a bit less robust that adding just the `target='_blank'`.

Comment (harshilsharma63) [reply webapp/src/utils.ts]: @jespino I've updated this to use `openInNewBrowser` only when available. Should be good now.

**Review by jespino — APPROVED** [review]
