### PR TITLE
Keep on sync the current team id with mattermost since the beginning

### LINKED ISSUE #3458: Bug: when accessing Boards through a link, the team is not highlighted
## Steps to reproduce the behavior

1. Go to a board on a multi-team instance
2. Reload

## Expected behavior

The team that my board is in should be highlighted

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2
 - Browser and OS: Firefox 102.0.1 on Linux

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
The selected team is handled by the mattermost-webapp code using the mattermost
store data, in this case the current team.

This PR forces to update the mattermost Channels current team id whenever it
changes on Boards.

#### Ticket Link
Fixes #3458

### CODE REVIEW

File: mattermost-plugin/webapp/src/index.tsx [hunk 1]
```diff
@@ -249,6 +249,17 @@ export default class Plugin {
             }
         })
 
+        let fbPrevTeamID = store.getState().teams.currentId
+        store.subscribe(() => {
+            const currentTeamID = store.getState().teams.currentId
+            if (currentTeamID && currentTeamID !== fbPrevTeamID) {
+                if (fbPrevTeamID && window.location.pathname.startsWith(windowAny.frontendBaseURL || '')) {
```
Comment (Rajat-Dabade) [inline mattermost-plugin/webapp/src/index.tsx:256]: Do we need this empty if check?

Comment (jespino) [reply mattermost-plugin/webapp/src/index.tsx:256]: :facepalm: clearly that isn't needed.

**Review by Rajat-Dabade — APPROVED** [review]
LGTM 👍

**Review by sbishel — APPROVED** [review]
