### PR TITLE
Reestructuring the router and splitting in more subcomponents

### LINKED ISSUE #2374: Permissions branch: New user unable to create board
## Steps to reproduce the behavior

This happens for a newly created user:

1. Register a new user ([invite link to test server](https://boards-permissions1.test.mattermost.cloud/signup_user_complete/?id=ytbsgkpeqtg3irhzzidm97kj3e))
2. Complete onboarding of user (set name, etc.)
3. Select Boards from App Switcher menu
4. Continue past the welcome screen
5. Click on the "Create empty board button"
6. Nothing happens, and errors in the console

## Expected behavior

A new board is created.

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

## Additional context

The URL after the welcome page when selecting Boards from the App Switcher is https://boards-permissions1.test.mattermost.cloud/boards/. Creating boards does not work from this URL.

If I click on the channel header button to open boards, the url is different (https://boards-permissions1.test.mattermost.cloud/boards/team/nnh4equh63gk3q1n7sfuix6kqe) and I can create a board.

This appears to be then persisted, and you can now open Boards from the App Switcher. However, you can repo this bug by clearing local storage, refreshing in Channels, then selecting Boards from the App Switcher.

### PR DESCRIPTION
**Pull request by jespino**
Fixes #2374

### CODE REVIEW

File: mattermost-plugin/webapp/src/index.tsx [hunk 1]
```diff
@@ -258,6 +258,11 @@ export default class Plugin {
             // @ts-ignore
             mmStore.dispatch(selectTeam(teamID))
         }
+        windowAny.getCurrentTeamId = (): string => {
```
Comment (jespino) [inline mattermost-plugin/webapp/src/index.tsx:261]: This is the part that helps with the redirection to the current channels team.

File: webapp/src/app.tsx [hunk 2]
```diff
@@ -142,165 +52,19 @@ const App = (): JSX.Element => {
...
-
-                                            return null
-                                        }}
-                                    />}
-                            </Switch>
-                        </div>
+                <div id='frame'>
+                    <div id='main'>
+                        <NewVersionBanner/>
+                        <FocalboardRouter/>
```
Comment (jespino) [inline webapp/src/app.tsx:65]: I removed everything here and replace it with the `FocalboardRouter` that is more or less the same but in an independent component.

File: webapp/src/route.tsx [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+type RouteProps = {
+    path: string|string[]
+    exact?: boolean
+    render?: (props: any) => React.ReactElement
+    children?: React.ReactElement
+    getOriginalPath?: (match: any) => string
+    loginRequired?: boolean
+}
+
+function FBRoute(props: RouteProps) {
```
Comment (jespino) [inline webapp/src/route.tsx:24]: I create a new concept of route, the FBRoute, this is just a route that accept some special parameters: `loginRequired` that forces to redirect to login when the user is not logged in, and the `getOriginalPath` that give you the redirect url for login and welcome pages.

This component ensure that if you are logged in but you haven't seen yet the welcome page, it is going to redirect you there, and with a redirect page if is needed.

Same for the login machinery.

File: webapp/src/router.tsx [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+                    viewId: match.params.viewId,
+                    cardId: match.params.cardId,
+                }))
+            }
+        })
+    }, [])
+    return null
+}
+
+function GlobalErrorRedirect() {
```
Comment (jespino) [inline webapp/src/router.tsx:73]: In transformed the global error redirect to a component that encapsulates that behavior.

File: webapp/src/router.tsx [hunk 5]
```diff
@@ -0,0 +1,208 @@
...
+const UUID_REGEX = new RegExp(/^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/)
+
+function HomeToCurrentTeam(props: {path: string, exact: boolean}) {
+    return (
+        <FBRoute
+            path={props.path}
+            exact={props.exact}
+            loginRequired={true}
+            render={() => {
+                const teamID = (window.getCurrentTeamId && window.getCurrentTeamId()) || ''
```
Comment (jespino) [inline webapp/src/router.tsx:40]: And here is where we get the current team from channels. I don't care about the lastTeamId visited because at the end of the day, this is the suite, so the last team visited is handled by mattermost itself, not by Focalboard. we have to be sure that when we switch teams that affects channels too, and that way it gets stored there too.

**Comment by harshilsharma63** [comment]
@jespino I'm unable to view the welcome page with fresh signup on this branch. See the attached video for demo - https://community-daily.mattermost.com/files/y43bxk6ns3f49pyfjxinxd5hah/public?h=ReTdWPbuUygGSyxFZBOG2ZsUiOP-MOhsQ6yAtuJzaUs

**Comment by jespino** [comment]
@harshilsharma63 addressed your comment, there was an infinite loop redirecting to the welcome page always. Now should be fixed.
