### PR TITLE
Read Mattermost s3 timeout value and used a default if not exist

### LINKED ISSUE #3773: Latest main - unable to create board from template with images
Getting following error when trying to create board with template with images in it -

```
{"timestamp":"2022-09-02 05:14:39.677 Z","level":"error","msg":"InitializeTemplates failed","caller":"app/plugin_api.go:975","plugin_id":"focalboard","error":"\"cannot initialize global templates for team 0: cannot import file 76fwrj36hptg6dywka4k5mt3sph.png for board bbn1888mprfrm5fjw9f1je9x3xo: unable write the data in the file g3kcuwxxat8sjgw57cpseq6rpe/0/b8orpp4yz3jg588655khfydhjba/76fwrj36hptg6dywka4k5mt3sph.png: context deadline exceeded\""}
```

Server URL - https://harshil-mysql-test-6.test.mattermost.cloud/team-a/channels/off-topic

Server invite link in Focalboard internal channel

### PR DESCRIPTION
**Pull request by harshilsharma63**
Fixes #3773

We weren't reading Mattermost's S3 timeout value. So when initialized the S3 client, the timeout used the default value of `int64`, which is 0. So upload requests timed out in 0 milliseconds.

### CODE REVIEW

File: mattermost-plugin/server/boards/boardsapp_util.go [hunk 1]
```diff
@@ -45,6 +47,11 @@ func createBoardsConfig(mmconfig mm_model.Config, baseURL string, serverID strin
 	if mmconfig.FileSettings.AmazonS3Trace != nil {
 		filesS3Config.Trace = *mmconfig.FileSettings.AmazonS3Trace
 	}
+	if mmconfig.FileSettings.AmazonS3RequestTimeoutMilliseconds == nil {
+		filesS3Config.Timeout = defaultS3Timeout
+	} else {
+		filesS3Config.Timeout = *mmconfig.FileSettings.AmazonS3RequestTimeoutMilliseconds
+	}
```
Comment (mgdelacroix) [inline mattermost-plugin/server/boards/boardsapp_util.go:54]: We can protect as well from a zero config value, in case somebody thinks that that would disable the timeout completely:

```suggestion
	filesS3Config.Timeout = defaultS3Timeout
	if mmconfig.FileSettings.AmazonS3RequestTimeoutMilliseconds != nil && *mmconfig.FileSettings.AmazonS3RequestTimeoutMilliseconds != 0 {
		filesS3Config.Timeout = *mmconfig.FileSettings.AmazonS3RequestTimeoutMilliseconds
	}
```

**Review by mgdelacroix — COMMENTED** [review]
Awesome!! :rocket: Suggested another check to ensure a user doesn't cause the client to be configured with timeout 0

File: mattermost-plugin/server/boards/boardsapp_util.go (hunk 1 above)
Comment (harshilsharma63) [reply mattermost-plugin/server/boards/boardsapp_util.go:54]: Such sense, much wow.

Comment (harshilsharma63) [reply mattermost-plugin/server/boards/boardsapp_util.go:54]: On it.

Comment (harshilsharma63) [reply mattermost-plugin/server/boards/boardsapp_util.go]: Done! Protected from 0 and negative timeout

**Review by mgdelacroix — APPROVED** [review]
:robot:

**Comment by harshilsharma63** [comment]
Verified with dev built from this PR on cloud server that image uploads work

**Comment by harshilsharma63** [comment]
Thanks @agnivade and @mgdelacroix for helping debug this!
