### PR TITLE
Fixes web files not found when plugin directory is custom

### LINKED ISSUE #592: Bug: server not bind to any port (mattermost-plugin)
Hello,

I have a port problem on the mattermost plugin for focalbord. The error message is as follows when I click on focalboard icon :

```
2021-06-18T10:41:39.832+0200 info go-plugin@v1.4.0/stream.go:15 {"level":"info","ts":1624005699.8301227,"caller":"server/server.go:206","msg":"Server.Start"} {"plugin_id": "focalboard", "source": "plugin_stderr"}
2021-06-18T10:41:39.833+0200 info go-plugin@v1.4.0/stream.go:15 2021/06/18 10:41:39 server not bind to any port {"plugin_id": "focalboard", "source": "plugin_stderr"}
2021-06-18T10:41:43.121+0200 info go-plugin@v1.4.0/stream.go:15 2021/06/18 10:41:43 Unable to serve the index.html fil, err: open plugins/focalboard/pack/index.html: no such file or directory {"plugin_id": "focalboard", "source": "plugin_stderr"}
```

This file exists on my disk (in `/opt/plugins/focalboard/pack/index.html`.  I have a custom entry for `PluginSettings.Directory` in my config.json.

I'm trying to set a port number in mattermost's config.json, in the PluginSettings entry, like other plugins, but it doesn't seem to do anything.
Nginx has been configured as indicated on your documentation.

### PR DESCRIPTION
**Pull request by mgdelacroix**
#### Summary
This PR solves plugin not correctly serving the frontend interface when used in a server with a custom plugin directory. Fixes #592 

#### Ticket Link
[Card](https://focalboard-community.octo.mattermost.com/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=47aa9bb4-6967-4a96-83c7-11bd6b20f1eb&v=612a901f-5c6d-4dde-8e35-3c16b6024a67&c=f8ad1709-b903-4172-8076-1b82649de09a)

### CODE REVIEW

File: mattermost-plugin/server/plugin.go [hunk 1]
```diff
@@ -90,7 +90,7 @@ func (p *Plugin) OnActivate() error {
 		DBTablePrefix:           "focalboard_",
 		UseSSL:                  false,
 		SecureCookie:            true,
-		WebPath:                 "./plugins/focalboard/pack",
```
Comment (jespino) [inline mattermost-plugin/server/plugin.go:93]: should we use `path.Join` here?

**Review by jespino — APPROVED** [review]
A comment that can be addressed later if we need it. but for now, I think this is ready to merge.

File: mattermost-plugin/server/plugin.go (hunk 1 above)
Comment (mgdelacroix) [reply mattermost-plugin/server/plugin.go:93]: I felt uneasy about it as our default value for the plugins directory is `./plugins` and putting it through `path.Join("./plugins", "focalboard/pack")` yields `plugins/focalboard/pack` without the `./`. In any case, I'll test it out and send another PR if it works fine with relative paths

Comment (mgdelacroix) [reply mattermost-plugin/server/plugin.go:93]: That and the fact that we do the same at the `ServerRoot` just seven lines above :P
