### PR TITLE
Fix bug on save on unmount

### LINKED ISSUE #809: Bug: Not able to rename a new card from "Untitled" (macOS & Win10)
Reproduced on AWS "latest" builds for macOS and Win10

**Summary:**
Text flashes between "Untitled" and "new_card_name" 

https://user-images.githubusercontent.com/13020833/127748317-18d681fd-0e40-48f1-a993-97e54dc37208.mp4

### PR DESCRIPTION
**Pull request by jespino**
Fix #809

### CODE REVIEW

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by harshilsharma63 — APPROVED** [review]

File: webapp/src/components/propertyValueElement.tsx [hunk 1]
```diff
@@ -48,9 +48,11 @@ const PropertyValueElement = (props:Props): JSX.Element => {
     const finalDisplayValue = displayValue || emptyDisplayValue
     const [open, setOpen] = useState(false)
 
+    const editableFields: Array<PropertyType> = ['text', 'number', 'email', 'url', 'phone']
+
     const saveTextProperty = useCallback(() => {
         if (editableFields.includes(props.propertyTemplate.type)) {
-            if (value !== props.card.fields.properties[props.propertyTemplate.id] || '') {
+            if (value !== (props.card.fields.properties[props.propertyTemplate.id] || '')) {
```
Comment (kamre) [inline webapp/src/components/propertyValueElement.tsx:55]: @jespino @wiggin77 can ESLint catch such conditions inside `if`? It seems that there is no much sense in using additional `|| ''` with boolean expression.
