### PR TITLE
Remove synthetic/implicit memberships for guests

### LINKED ISSUE #3771: Bug: Guests can access boards linked to a channel
## Steps to reproduce the behavior

1. Invite a guest to a channel
2. Link boards to the same channel
3. Login as the guest
4. Go to the channel and click on the boards linked on the channel
5. See error - guest is able to access those boards even though they're not an explicit member

## Expected behavior

Guests should not have access any board unless they were added as an explicit member. See [this thread](https://community.mattermost.com/private-core/pl/dpw8uj3dbpdsijdobueacp7kyc) for reference.

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/188013397-d4bc393e-b5ca-40e7-9d2c-bae016aa9b68.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.3
 - Browser and OS: Chrome on Mac

### PR DESCRIPTION
**Pull request by Pinjasaur**
#### Summary

See #3771 for details, but the concept of having a synthetic membership for a _guest_ is removed. They will need to be explicitly added to a board via the Share modal.

See #3785 for tracking of the modal dialog copy to reflect this change. cc @wuwinson 

#### Ticket Link

closes #3771

### CODE REVIEW

File: server/services/store/mattermostauthlayer/mattermostauthlayer.go [hunk 1]
```diff
@@ -739,6 +739,14 @@ func (s *MattermostAuthLayer) implicitBoardMembershipsFromRows(rows *sql.Rows) (
 }
 
 func (s *MattermostAuthLayer) GetMemberForBoard(boardID, userID string) (*model.BoardMember, error) {
+	// No synthetic memberships for guests
+	user, err := s.GetUserByID(userID)
+	if err != nil {
+		return nil, err
+	}
+	if user.IsGuest {
+		return nil, nil
```
Comment (wiggin77) [inline server/services/store/mattermostauthlayer/mattermostauthlayer.go:748]: I would like to see us move away from methods that return `nil,nil`.  It is very common for developers to expect if error=nil then the other value is valid.  

Some alternatives would be to return an error if IsGuest, or return three values (*model.BoardMember, bool, error) where the bool signifies if member was found.

Comment (Pinjasaur) [reply server/services/store/mattermostauthlayer/mattermostauthlayer.go:748]: Thanks @wiggin77, I was suspecting this might be an anti-pattern. I think I'd personally prefer keeping with the tuple return unless there's some side effect I'm not considering. Any preference on a specific error type or just do an `errors.New`?

Comment (jespino) [reply server/services/store/mattermostauthlayer/mattermostauthlayer.go:748]: This is not correct, a Guest can be member of a board, in this case you are saying that doesn't matter what board are you querying that if the member is a guest, it has no membership.

It should check for the guest only in the case of the explicit membership is not found.

Comment (jespino) [reply server/services/store/mattermostauthlayer/mattermostauthlayer.go:748]: About what to return, I would expect a "NotFound" error here.

File: server/services/store/mattermostauthlayer/mattermostauthlayer.go [hunk 2]
```diff
@@ -868,7 +886,12 @@ func (s *MattermostAuthLayer) GetMembersForBoard(boardID string) ([]*model.Board
 		existingMembers[m.UserID] = true
 	}
 	for _, m := range implicitMembers {
-		if !existingMembers[m.UserID] {
+		// No synthetic memberships for guests
+		user, err := s.GetUserByID(m.UserID)
```
Comment (jespino) [inline server/services/store/mattermostauthlayer/mattermostauthlayer.go:890]: This is going to be really awful in performance, this is generating one DB roadtrip for each implicit memberships here.

Comment (jespino) [reply server/services/store/mattermostauthlayer/mattermostauthlayer.go:890]: My suggestion here is to use the original query to extract the data, another extra join to get the User information, now know if the user there is a guest or not.

File: server/services/store/mattermostauthlayer/mattermostauthlayer.go (hunk 1 above)
Comment (Pinjasaur) [reply server/services/store/mattermostauthlayer/mattermostauthlayer.go:758]: Thanks @jespino, good catch.

**Comment by Pinjasaur** [comment]
Would like someone's input on the addition to the query to make sure that looks good. Additionally the `/boards/search` API will need to be updated to only include boards that guests are explicit members of. See #3771.

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Comment by Pinjasaur** [comment]
> @Pinjasaur - Can this be merged?

@sbishel nearly, just need to update the `/boards/search` endpoint as mentioned above. That was my intention today along with a PR for #3785 to update the modal copy based on these changes.

**Review by jespino — APPROVED** [review]
LGTM

**Comment by Pinjasaur** [comment]
@sbishel should be good to go, if you could give the changes to `/boards/search` endpoint a once-over: [`fe0121b` (#3786)](https://github.com/mattermost/focalboard/pull/3786/commits/fe0121b33ea032f9564743e0bc85eb4f68bbd653)

**Review by sbishel — APPROVED** [review]
