### PR TITLE
Fixing Issue 3124

### LINKED ISSUE #3124: Bug: "Your action hidden another card" message showing up before the limit is reached
## Steps to reproduce the behavior

1. Go to a server with cloud limits - https://boards-bugbash-7rc.test.mattermost.cloud/
2. Log in as a sysadmin and go to System Console > Subscription
3. Note that there's only ~80 cards on the server
4. Go to Boards
5. Create a card 
6. Note the "Your action hidden another card" message

## Expected behavior

"Your action hidden another card" message shouldn't show up before the 500 card limit is reached

## Screenshots (optional)

image

image

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0
 - Browser and OS: Chrome on Windows

### PR DESCRIPTION
**Pull request by jespino**
Fixes #3124

### CODE REVIEW

File: webapp/src/components/cardLimitNotification.tsx [hunk 1]
```diff
@@ -79,7 +79,7 @@ const CardLimitNotification = () => {
         title = intl.formatMessage(
             {
                 id: 'notification-box-cards-hidden.title',
-                defaultMessage: 'This action hid another card',
+                defaultMessage: 'This action hide another card',
```
Comment (sbishel) [inline webapp/src/components/cardLimitNotification.tsx:82]: 'hid' is correct per https://github.com/mattermost/focalboard/pull/3151

```suggestion
                defaultMessage: 'This action hid another card',
```

**Review by sbishel — CHANGES_REQUESTED** [review]
Just a grammer fix needed.

**Review by sbishel — APPROVED** [review]
