### PR TITLE
Fixed a bug preventing any navigation in Mattermost desktop with subpath

### LINKED ISSUE #2027: Bug: Boards not working (Mattermost 5.39->6.2.1 upgrade) with SiteURL
## Edition and Platform

 - Edition: Mattermost plugin
 - Version: Mattermost 6.2.1 (Linux x64, Ubuntu Server 20.04.2)
 - Browser and OS: Mattermost Desktop App - Windows 10 & Ubuntu 21.04

## The Problem

I updated our Mattermost server to 6.2.1 (from 5.39.0), using the basic method suggested by the upgrade guide (which I’ve done many times previously), and boards aren’t working.

I do see the list of channels/boards, but attempting to view a channel’s board(s) results in:

> The team you’re requesting is private or does not exist. Please contact your Administrator for an invitation.

I’m a member of the team, and the administrator. Other (non-admin) team members see the same issues.

The log contains:

```
{"timestamp":"2021-12-30 12:32:49.822 +11:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"403","error":"\"access denied to workspace\"","_msg":"\"Access denied to workspace\"","api":"/api/v1/workspaces/0/users"}
{"timestamp":"2021-12-30 12:32:49.825 +11:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"401","error":"","_msg":"\"user does not have workspace access\"","api":"/api/v1/workspaces/0"}
```

Clicking “Back to mattermost” brings me to a page where I can “Log in again”, which gives me a 404 and the following error in the log:

```
{"timestamp":"2021-12-30 12:33:06.241 +11:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:924","plugin_id":"focalboard","code":"401","error":"\"unable to delete the session: no update allowed from focalboard, update it using mattermost\"","_msg":"\"incorrect login\"","api":"/api/v1/logout"}
```

I’ve tried resetting the desktop app cache, ensured all server file permissions are set appropriately, restarted the mattermost service and apache proxy multiple times. Tried logging out and back in to renew my session.

I was previously using focalboard as an external client plugin before it was integrated - I removed that copy from `client/plugins` but it didn’t change anything. I tried removing/re-adding/enabling the new integrated plugin but no change.

The rest of Mattermost seems to be working fine…

### PR DESCRIPTION
**Pull request by harshilsharma63**
Fixes #2027

On the Mattermost desktop app, navigation in boards doesn't work if you are on a subpath. This PR, along with fixes in the latest unreleased desktop app fixes this issue.

To test this, you need to install the desktop app from the `master` branch, or download the latest nightly from [Desktop Builds](https://community-daily.mattermost.com/core/channels/desktop-builds) channel.

Thanks a ton, @devinbinnie for looking into this 🙌

### CODE REVIEW

File: mattermost-plugin/webapp/src/index.tsx [hunk 1]
```diff
@@ -87,12 +87,12 @@ function customHistory() {
             }
 
             const pathName = event.data.message?.pathName
-            if (!pathName || !pathName.startsWith(windowAny.frontendBaseURL)) {
```
Comment (jespino) [inline mattermost-plugin/webapp/src/index.tsx:90]: This solution would break things like having focalboard in a subpath

**Review by jespino — CHANGES_REQUESTED** [review]
This is not the proper solution because can break subpath instances

File: mattermost-plugin/webapp/src/index.tsx (hunk 1 above)
Comment (harshilsharma63) [reply mattermost-plugin/webapp/src/index.tsx:90]: @jespino this is needed to make subpaths work in the desktop app. This code doesn't affect the ability to run Focalboard with subpath in browsers.

**Review by jespino — APPROVED** [review]
Ohh, sorry, I didn't realize that. You are right.
