### PR TITLE
Fixed migrations to allow upgrading from previous version

### LINKED ISSUE #2470: Permissions feature Bug: cannot upgrade from 0.14 to latest permissions branch
## Steps to reproduce the behavior

Install 0.14 and upgrade to the latest permissions branch.

Error in server logs-

```
Table creation / migration failed","caller":"app/plugin_api.go:931","plugin_id":"focalboard","error":"\"driver: mysql, message: failed to fetch applied migrations, command: select_applied_migrations, originalError: Error 1054: Unknown column 'name' in 'field list', query: \n\nSELECT version, name FROM focalboard_schema_migrations
```

## Expected behavior

You should be able to upgrade.

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed a bunch of issues related to upgrading from a previous installation to the permissions branch.

Tasks handled -

1. Migrate the schema migrations table to the format reviewed by gomorph.
2. Fixed a few JSON issues with MySQL.

#### Ticket Link
Fixes #2470

### CODE REVIEW

File: server/services/store/sqlstore/migrate.go [hunk 1]
```diff
@@ -213,6 +225,194 @@ func (s *SQLStore) Migrate() error {
 	return engine.ApplyAll()
 }
 
+func (s *SQLStore) migrateSchemaVersion(migrations []*models.Migration) error {
```
Comment (isacikgoz) [inline server/services/store/sqlstore/migrate.go:228]: Naming is hard, but we are actually migrating the migration system. Can you update the naming accordingly and also add a few line of comments why this was needed etc.

File: server/services/store/sqlstore/migrate.go [hunk 2]
```diff
@@ -213,6 +225,194 @@ func (s *SQLStore) Migrate() error {
...
+	var count int
+	if err := row.Scan(&count); err != nil {
+		s.logger.Error("failed to check for columns of schema_migrations table", mlog.Err(err))
+		return false, err
+	}
+
+	return count == 1, nil
+}
+
+func (s *SQLStore) isSchemaMigrationNeededSQLite() (bool, error) {
```
Comment (isacikgoz) [inline server/services/store/sqlstore/migrate.go:288]: Out of curiosity since I didn't worked too much with SQLite; What if we try to read from the table and try get the `dirty` value even if the column does not exists? Wouldn't it fail? Maybe we can understand that way..

File: server/services/store/sqlstore/migrate.go [hunk 3]
```diff
@@ -213,6 +225,194 @@ func (s *SQLStore) Migrate() error {
...
+		}
+	}
+
+	return nameColumnFound, nil
+}
+
+func (s *SQLStore) getLegacySchemaVersion() (uint32, error) {
+	query := s.getQueryBuilder(s.db).
+		Select("version").
+		From(s.tablePrefix + "schema_migrations")
```
Comment (isacikgoz) [inline server/services/store/sqlstore/migrate.go:336]: Maybe we should just store `s.tablePrefix + "schema_migrations"` value somewhere. It's being used many times.

File: server/services/store/sqlstore/migrate.go [hunk 4]
```diff
@@ -213,6 +225,194 @@ func (s *SQLStore) Migrate() error {
...
+
+	return nil
+}
+
+func (s *SQLStore) useNewSchemaTable() error {
+	// first delete the old table, then
+	// rename the new table to old table's name
+
+	// deleting old table
+	query := "DROP TABLE " + s.tablePrefix + "schema_migrations"
```
Comment (isacikgoz) [inline server/services/store/sqlstore/migrate.go:395]: Before deleting, should we just try to rename this? Then use new one, then delete this one.

**Review by isacikgoz — COMMENTED** [review]
We need to find a way to lock database before running these, cluster mutex can come handy. Additionally, I have some questions and comments below.

File: server/services/store/sqlstore/migrate.go (hunk 2 above)
Comment (harshilsharma63) [reply server/services/store/sqlstore/migrate.go:288]: What difference would it make? Any issue with the current implementation?

File: server/services/store/sqlstore/migrate.go (hunk 1 above)
Comment (harshilsharma63) [reply server/services/store/sqlstore/migrate.go:228]: Done.

File: server/services/store/sqlstore/migrate.go (hunk 3 above)
Comment (harshilsharma63) [reply server/services/store/sqlstore/migrate.go:336]: We don't do that anywhere in Focalboard.

File: server/services/store/sqlstore/migrate.go (hunk 4 above)
Comment (harshilsharma63) [reply server/services/store/sqlstore/migrate.go]: Done.

**Comment by harshilsharma63** [comment]
> We need to find a way to lock database before running these, cluster mutex can come handy. Additionally, I have some questions and comments below.

Focalboard was already creating a lock for running migrations. I moved my code after the point we acquire the lock. This should resolve the issue.

**Review by jespino — APPROVED** [review]
LGTM, just a small detail around a logger that I think was there for debug.
