### PR TITLE
Fix @-mentions in boards & for guests

### LINKED ISSUE #2604: Bug: Guest User can @mention users from other teams
## Steps to reproduce the behavior

1. Create a User in TeamA.
2. Create a guest user and add to TeamB
3. Login as Guest User
4. Go to boards
5. Select a card. Attempt to @mention User in TeamA

## Expected behavior
Guest users should not be able to @mention users in other teams.

### PR DESCRIPTION
**Pull request by Pinjasaur**
#### Summary

Fixing bugs related to `@mention`s and Guest accounts:
- filter the in-memory board users list for private boards (where the Redux state is used, no API calls)
- fix in an invalid DB query for searching users as a guest
- handle `includePublicBoards` when getting boards for a user & team
- don't use the API search for users when `@mention`ing as a guest

#### Ticket Link

closes #2604 

cc @wuwinson @jespino this should handle #3746 as-is too (intentionally not using a closing keyword there 🙂)

### CODE REVIEW

File: server/services/store/mattermostauthlayer/mattermostauthlayer.go [hunk 1]
```diff
@@ -860,13 +860,21 @@ func (s *MattermostAuthLayer) GetBoardsForUserAndTeam(userID, teamID string, inc
...
+	if includePublicBoards {
+		boards, err := s.SearchBoardsForUserInTeam(teamID, "", userID)
+		if err != nil {
+			return nil, err
+		}
+		for _, b := range boards {
+			boardIDs = append(boardIDs, b.ID)
+		}
+	}
+
```
Comment (Pinjasaur) [inline server/services/store/mattermostauthlayer/mattermostauthlayer.go:877]: @jespino any problems you see with this approach?

**Review by sbishel — APPROVED** [review]
