### PR TITLE
[GH-1946] Fix losing focus for the card title in the dialog

### LINKED ISSUE #1877: Bug: at-mention autocomplete shows up in the top left after dismissing it and engaging it again
## Steps to reproduce the behavior

1. Go to Boards
2. Open a card
3. In the comment box, type "@"
4. Note the autocomplete shows up
5. Click outside of the comment box
6. Click inside the comment box again - note the dropdown shows up in the top left of the screen

## Expected behavior

Autocomplete dropdown should show up below the input field

## Screenshots

Screenshot (54)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.11
 - Browser and OS: Chrome & Firefox

### LINKED ISSUE #1946: Bug: When creating a new card the focus is not put on the title of the card
## Steps to reproduce the behavior

1. On a board add a new card
2. The system will popup a dialog to create the new card
3. You'll see that the textinput is shown very briefly on the title line but disappears after a couple of seconds

## Expected behavior

When creating a new card I would expect the focus to be on the title field (I even would expect the focus on that field when editing an existing card). This allows users to more easily and quickly create cards without performing additional clicks.

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop 
 - Version: 0.11 RC2
 - Browser and OS: Windows 10

### PR DESCRIPTION
**Pull request by kamre**
#### Summary
Don't set focus for `MarkdownEditorInput` on mount if it is not in editing state.
Also fixes `at-mention` popup appearing in top-right corner of screen after re-focus.

#### Ticket Link
Fixes #1946
Fixes #1877

### CODE REVIEW

File: webapp/src/components/markdownEditorInput/markdownEditorInput.tsx [hunk 1]
```diff
@@ -74,17 +74,9 @@ const MarkdownEditorInput = (props: Props): ReactElement => {
...
-        if (isEditing && isMounted) {
+        if (isEditing) {
             setEditorState(EditorState.moveSelectionToEnd(editorState))
-        }
-
-        return () => {
-            isMounted = false
+            setTimeout(() => ref.current?.focus(), 200)
         }
     }, [isEditing])
```
Comment (hahmadia) [inline webapp/src/components/markdownEditorInput/markdownEditorInput.tsx:81]: Nice @kamre! You're the man!
Oddly enough, I tested this locally and this not only solves the problem you've pointed out, but also solves #1877.

Can you just make the following changes to the `useEffect` underneath this? It should end up looking like
```JS
    useEffect(() => {
        if (isEditing) {
            setEditorState(EditorState.moveSelectionToEnd(editorState))
            setTimeout(() => ref.current?.focus(), 200)
        }
    }, [isEditing])

    useEffect(() => {
        if (initialText === '' && !isEditing) {
            setTimeout(() => {
                setEditorState(EditorState.createEmpty())
            }, 200)
        }
    }, [initialText, isEditing])
 ```
 
 I had to make those additional changes because I noticed that when I click in on a comment and type my first letter, it takes the cursor to the beginning. 
 
 Once it's made, re-request a re-review and I'll approve. Thanks!

**Review by hahmadia — CHANGES_REQUESTED** [review]

File: webapp/src/components/markdownEditorInput/markdownEditorInput.tsx (hunk 1 above)
Comment (kamre) [reply webapp/src/components/markdownEditorInput/markdownEditorInput.tsx:81]: @hahmadia I have made the changes that you propose and it indeed helps with the cursor positioning!

But I have also noticed that when all the text is removed and `onBlur` is performed then next text editing seems to be broken.

**Review by hahmadia — APPROVED** [review]
LGTM! 👍 

Expediting this PR as it solves a regression and another bug that need to be back-ported to 0.11.

**Review by ogi-m — APPROVED** [review]
Tested and passed, both issues are fixed by this 🎉

**Comment by kamre** [comment]
@ogi-m can you please also check this scenario:

* click on Add a description in the card dialog
* enter some text (cursor works fine)
* press Esc for onBlur event
* click for editing
* remove all the text
* press Esc for onBlur event
* there will be Edit text placeholder

Now try to edit text couple of times, it seems that editing of the text is broken.

**Comment by ogi-m** [comment]
@kamre This is what I'm seeing:

1. click on Add a description in the card dialog
2. enter some text (cursor works fine)
3. press Esc for onBlur event
4. click for editing
5. remove all the text
6. press Esc for onBlur event
7. Click again and enter some text
8. press Esc for onBlur event
9. Click the field again to edit - the text entered in step 7 is gone

**Comment by hahmadia** [comment]
@ogi-m Please test to ensure all bugs have been addressed. Thank you

**Review by ogi-m — APPROVED** [review]
LGTM 👍🏻
