### PR TITLE
Missing board options in sidebar

### LINKED ISSUE #2640: Permission Branch: Missing options to duplicate board and create new template from board
## Steps to reproduce the behavior

1. Create a new board
2. Click on the "..." menu next to the board name on the sidebar
3. See error

## Expected behavior

Menu should have options for:
- Duplicate board
- New template from board

## Screenshots (optional)

| Permissions Branch  | Community |
|--|--|
| Screen Shot 2022-03-25 at 12 59 32 PM | Screen Shot 2022-03-25 at 1 02 13 PM |

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

### PR DESCRIPTION
**Pull request by harshilsharma63**
Fixes #2640

### CODE REVIEW

File: webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx [hunk 1]
```diff
@@ -38,7 +39,9 @@ const BoardTemplateSelectorItem = (props: Props) => {
         >
             <span className='template-icon'>{template.icon}</span>
             <span className='template-name'>{template.title}</span>
-            {!template.templateVersion &&
```
Comment (harshilsharma63) [inline webapp/src/components/boardTemplateSelector/boardTemplateSelectorItem.tsx:41]: Replacing `template.templateVersion` with `template.teamId` check to fix a case where you create a board from a default template then convert that board again to a template. Template version stays the same all across, so we end up with edit and delete options hidden incorrectly from this template.

File: webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx [hunk 2]
```diff
@@ -231,7 +231,6 @@ describe('components/boardTemplateSelector/boardTemplateSelector', () => {
             const editIcon = screen.getByText(template1Title).parentElement?.querySelector('.EditIcon')
             expect(editIcon).not.toBeNull()
             userEvent.click(editIcon!)
-            expect(history.push).toBeCalledTimes(1)
```
Comment (harshilsharma63) [inline webapp/src/components/boardTemplateSelector/boardTemplateSelector.test.tsx:234]: Removed this as this has been moved into utils, and utils are mocked here. I've added new tests for utils to test this functionality.

**Review by sbishel — APPROVED** [review]
LGTM
