### PR TITLE
fix: display non-explicit members in Share Board modal <Select>

### LINKED ISSUE #3808: Bug: Cannot create explicit membership for implicit member
## Steps to reproduce the behavior

1. Create a board with a channel association. 
2. In share dialog, attempt to find a member of the channel 
3. Channel members are not displayed, so you cannot choose one.

## Expected behavior

Channel members should be available to create explicit membership.

## Screenshots (optional)
Screen Shot 2022-09-08 at 12 26 10 PM
Screen Shot 2022-09-08 at 12 28 16 PM

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3.0-rc1
 - Browser and OS: [Chrome on Mac]

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 2: Affects major functionality with a difficult or non-obvious workaround

### PR DESCRIPTION
**Pull request by Pinjasaur**
#### Summary

Previously, the `<Select>` in the Share Board modal was only filtering on if the user was a member of the board, regardless of explicit or implicit type. This fixes the logic to include implicit members so they could be made explicit if desired.

#### Ticket Link

closes #3808

### CODE REVIEW

File: webapp/src/components/shareBoard/shareBoard.tsx [hunk 1]
```diff
@@ -360,7 +360,13 @@ export default function ShareBoardDialog(props: Props): JSX.Element {
                             value={selectedUser}
                             className={'userSearchInput'}
                             cacheOptions={true}
-                            filterOption={(o) => !members[o.value]}
+                            filterOption={(o) => {
+                                // render non-explicit members
+                                if (members[o.value])
+                                    return members[o.value].synthetic
```
Comment (sbishel) [inline webapp/src/components/shareBoard/shareBoard.tsx:366]: This style will cause lint errors, once that PR gets merged. 
```suggestion
                                if (members[o.value]) {
                                    return members[o.value].synthetic
                                }
```

**Review by sbishel — APPROVED** [review]
Approving with recommended change which will cause linter errors.
