### PR TITLE
Avoided boards from navigating to URL not belonging to it

### LINKED ISSUE #1452: Bug: Desktop App: Clicking on the unread filter in Channels sometimes opens the Boards dashboard
## Steps to reproduce the behavior

1. Open the Mattermost Desktop App v5.0 (RC2)
2. Click on the unread threads filter button in Channels
3. Sometimes the Boards dashboard opens

## Expected behavior

The Boards view should not open

## Screenshots

unread thread button

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2
 - Browser and OS: Desktop App v5 RC2

### LINKED ISSUE #1453: Bug: Desktop App: Clicking on the back button sometimes opens Boards
## Steps to reproduce the behavior

1. Open the Mattermost Desktop App v5.0 (RC2)
2. Click on the back button in Channels
3. Sometimes the Boards dashboard opens

## Expected behavior

The Boards view should not open

## Screenshots
https://user-images.githubusercontent.com/46905241/136068894-f3bec8eb-eff6-484a-a138-8333804a8f6e.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.1 RC2
 - Browser and OS: Desktop App v5 RC2

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Avoided boards from navigating to URL not belonging to it.

#### Ticket Link
Fixes #1452 
Fixes #1453

### CODE REVIEW

File: webapp/src/app.tsx [hunk 1]
```diff
@@ -47,10 +47,11 @@ if (Utils.isDesktop() && Utils.isFocalboardPlugin()) {
         }
 
         const pathName = event.data.message?.pathName
-        if (!pathName) {
+        if (!pathName || !pathName.startsWith((window as any).frontendBaseURL)) {
             return
         }
 
+        Utils.log(`Navigating Boards to ${pathName}`)
```
Comment (jespino) [inline webapp/src/app.tsx:54]: Is this new log entry still necessary?

**Review by jespino — APPROVED** [review]
LGTM. Just a question about a `Utils.log` call that is not an stopper at all.

File: webapp/src/app.tsx (hunk 1 above)
Comment (harshilsharma63) [reply webapp/src/app.tsx:54]: I wanted to keep this as it could help us figure out similar issues in the near future.
