### PR TITLE
fix: filter out bots for sharing, @mention-ing, and Person property

### LINKED ISSUE #3656: Bug: Bots show up in Share Board Search
## Steps to reproduce the behavior

1. Go to Share on a board you are an admin
2. Type 'B'
3. Notice the user "Boards", which is a bot is available

## Expected behavior

Bots should not be displayed as users for board access.

## Screenshots (optional)
Screen Shot 2022-08-11 at 12 17 30 PM

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.0-rc3
 - Browser and OS: Chrome on Mac,

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

### PR DESCRIPTION
**Pull request by Pinjasaur**
#### Summary

Filters out bots when sharing a board, `@mention`-ing a user, and the Person property by adding an `?exclude_bots=true` query param to the `/teams/{teamID}/users` API endpoint.

#### Ticket Link

fixes #3656

### CODE REVIEW

**Review by sbishel — CHANGES_REQUESTED** [review]
One issue I see with this approach is we limit the returned items to 10. If one is a bot, then we will only display 9 users, which is not a huge deal. However, if you were to search on 'bot' and there were a lot of "bot" accounts. Then we may display only display say 2 and a legitimate name containing `bot` would not be returned. Therefore, we probably need to move this server side.

**Comment by Pinjasaur** [comment]
> One issue I see with this approach is we limit the returned items to 10. If one is a bot, then we will only display 9 users, which is not a huge deal. However, if you were to search on 'bot' and there were a lot of "bot" accounts. Then we may display only display say 2 and a legitimate name containing `bot` would not be returned. Therefore, we probably need to move this server side.

Ahh, good point @sbishel. Is there a preference towards how it's implemented API-wise e.g. `?no_bots=true` query param or something else? cc @wiggin77 for API opinions 🙂

**Comment by wiggin77** [comment]
> `?no_bots=true` query param or something else? cc @wiggin77 for API opinions

Query string is fine for now, but I suspect we'll move these into a QueryUserOptions struct that will be passed in the body.  This better matches how the Channels equivalent APIs work, and allows us to easily add more search criteria.

Currently the getTeamsUsers on the backend does not support a filter to exclude bot.  That will need to be added, but the underlying store API `getUsersByCondition` can have any condition added. `Users` has an `isBot` flag to filter on.

IMO the searchUsersByTeam and getUsersByTeam should be passed a QueryUsersOptions struct that contains TeamID, SearchQuery, ExcludeBots, and we can add to it.  This can be done later.   Thanks @Pinjasaur

File: Makefile [hunk 1]
```diff
@@ -100,7 +100,7 @@ server-linux-package-docker:
 	rm -rf package
 
 generate: ## Install and run code generators.
-	cd server; go get github.com/golang/mock/mockgen
+	cd server; go install github.com/golang/mock/mockgen@v1.6.0
```
Comment (Pinjasaur) [inline Makefile:103]: the install instructions changed for recent golang versions https://github.com/golang/mock#go-116

File: server/services/store/sqlstore/user.go [hunk 2]
```diff
@@ -218,7 +218,7 @@ func (s *SQLStore) getUsersByTeam(db sq.BaseRunner, _ string, _ string) ([]*mode
 	return s.getUsersByCondition(db, nil, 0)
 }
 
-func (s *SQLStore) searchUsersByTeam(db sq.BaseRunner, _ string, searchQuery string, _ string) ([]*model.User, error) {
+func (s *SQLStore) searchUsersByTeam(db sq.BaseRunner, _ string, searchQuery string, _ string, _ bool) ([]*model.User, error) {
```
Comment (Pinjasaur) [inline server/services/store/sqlstore/user.go:221]: there are no bot users in non-plugin mode so the only real business logic change is in mattermostauthlayer.go

File: server/api/teams.go [hunk 3]
```diff
@@ -217,6 +222,7 @@ func (a *API) handleGetTeamUsers(w http.ResponseWriter, r *http.Request) {
 	userID := getUserID(r)
 	query := r.URL.Query()
 	searchQuery := query.Get("search")
+	excludeBots := r.URL.Query().Get("exclude_bots") == True
```
Comment (wiggin77) [inline server/api/teams.go:225]: Looking good.  It's unfortunate that the previous behaviour was to include bots, since I think most usage of this API will exclude bots and it would be nice to have that as the default (i.e. no param provided).

Comment (Pinjasaur) [reply server/api/teams.go:225]: @wiggin77 could we make that change in the v3 you're working on?

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:

**Review by sbishel — APPROVED** [review]
