### PR TITLE
Fixing delete/undelete boards

### LINKED ISSUE #2566: Permissions Branch: Undo delete board doesn't work
## Steps to reproduce the behavior

1. Create a board
2. Delete it from the sidebar menu
3. Press Cmd+Z to undo
4. Error page is shown ("Board not found")

## Expected behavior

Board is un-deleted and shown

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: permissions-feature-branch
 - Browser and OS: Chrome on Mac

### PR DESCRIPTION
**Pull request by jespino**
Fixes #2566

### CODE REVIEW

File: server/api/api.go [hunk 1]
```diff
@@ -1062,6 +1063,53 @@ func (a *API) handleUndeleteBlock(w http.ResponseWriter, r *http.Request) {
...
+	userID := session.UserID
+
+	vars := mux.Vars(r)
+	boardID := vars["boardID"]
+
+	auditRec := a.makeAuditRecord(r, "undeleteBoard", audit.Fail)
+	defer a.audit.LogRecord(audit.LevelModify, auditRec)
+	auditRec.AddMeta("boardID", boardID)
+
+	err := a.app.UndeleteBoard(boardID, userID)
```
Comment (wiggin77) [inline server/api/api.go:1101]: Can anyone with a valid session undelete a board if they know the ID?

Comment (jespino) [reply server/api/api.go:1101]: Good question, we should have the permission to create the board of the right type.

Comment (jespino) [reply server/api/api.go:1116]: Added permissions checks for `undeleteBoard` and for `undeleteBlock` and some tests.

**Comment by jespino** [comment]
@wuwinson @chenilim I'm using the `delete_board` permission for undelete boards and the `manage_board_cards` for the undelete block, I hope that is correct, I'm almost 100% sure about the later, but I have some doubts about the former.

File: webapp/src/octoClient.ts [hunk 2]
```diff
@@ -335,9 +335,17 @@ class OctoClient {
...
+    async undeleteBlock(boardId: string, blockId: string): Promise<Response> {
         Utils.log(`undeleteBlock: ${blockId}`)
-        return fetch(this.getBaseURL() + this.teamPath() + `/blocks/${encodeURIComponent(blockId)}/undelete`, {
+        return fetch(`${this.getBaseURL()}/api/v1/boards/${encodeURIComponent(boardId)}/blocks/${encodeURIComponent(blockId)}/undelete`, {
+            method: 'POST',
+            headers: this.headers(),
+        })
+    }
+
+    async undeleteBoard(boardId: string): Promise<Response> {
```
[the remark this answers is not in the document]
Comment (wiggin77) [reply webapp/src/octoClient.ts:346]: Sorry - that doesn't make sense here.  I guess I'm confused about how someone undeletes a board and all the cards and blocks.

[the remark this answers is not in the document]
Comment (jespino) [reply webapp/src/octoClient.ts:346]: Yes, now we don't have cascade deletion, you delete the board, is enough because the board info is not longer accesible (from the UI perspective), in the future we can decide to cascade that, or to interpret a block in a deleted board as deleted. But... For now, we only need the undelete of the board.

File: server/api/api.go [hunk 3]
```diff
@@ -1103,6 +1104,58 @@ func (a *API) handleUndeleteBlock(w http.ResponseWriter, r *http.Request) {
...
+
+	vars := mux.Vars(r)
+	boardID := vars["boardID"]
+
+	auditRec := a.makeAuditRecord(r, "undeleteBoard", audit.Fail)
+	defer a.audit.LogRecord(audit.LevelModify, auditRec)
+	auditRec.AddMeta("boardID", boardID)
+
+	if !a.permissions.HasPermissionToBoard(userID, boardID, model.PermissionDeleteBoard) {
+		a.errorResponse(w, r.URL.Path, http.StatusForbidden, "", PermissionError{"access denied to create public boards"})
```
Comment (wiggin77) [inline server/api/api.go:1143]: I don't think this is the right error text for this condition.

File: server/services/store/sqlstore/board.go [hunk 4]
```diff
@@ -691,6 +691,98 @@ func (s *SQLStore) getBoardHistory(db sq.BaseRunner, boardID string, opts model.
...
 
+func (s *SQLStore) undeleteBoard(db sq.BaseRunner, boardID string, modifiedBy string) error {
+	boards, err := s.getBoardHistory(db, boardID, model.QueryBoardHistoryOptions{Limit: 1, Descending: true})
+	if err != nil {
+		return err
+	}
+
+	if len(boards) == 0 {
+		s.logger.Warn("undeleteBlock board not found", mlog.String("board_id", boardID))
+		return nil // deleting non-exiting board is not considered an error (for now)
```
Comment (wiggin77) [inline server/services/store/sqlstore/board.go:702]:
```suggestion
		return nil // undeleting non-exiting board is not considered an error (for now)
```

File: server/api/api.go (hunk 3 above)
Comment (jespino) [reply server/api/api.go:1143]: You are totally right 🤦‍♂️

Comment (jespino) [reply server/api/api.go]: Done!

**Review by wiggin77 — APPROVED** [review]
LGTM :+1:
