### PR TITLE
Sorted categories on modification or creation

### LINKED ISSUE #2809: Bug: New categories don't automatically sort in alphabetical order
## Steps to reproduce the behavior

1. Go to sidebar with existing custom categories
2. Select the "..." from any category
3. Select "Create a New Category"
4. Name the category "AAA"
5. See error - category appears above the default "Boards" category, but below all the other custom categories

## Expected behavior

The "AAA" category should appear at the top or near the top of the sidebar. Sidebar only updates to the proper sort order when going to Channels then back to Boards.

## Screenshots (optional)

Screen Shot 2022-04-14 at 1 43 46 PM

## Edition and Platform

- Edition: Mattermost Boards (plugin)
- Version: v0.16 (bugbash)
- Browser and OS: Chrome on Mac

### PR DESCRIPTION
**Pull request by harshilsharma63**
Fixes #2809

### CODE REVIEW

File: webapp/src/store/sidebar.ts [hunk 1]
```diff
@@ -68,6 +68,9 @@ const sidebarSlice = createSlice({
                         updateAt: updatedCategory.updateAt,
                     }
                 }
+
+                // sort categories alphabetically
+                state.categoryAttributes.sort((a, b) => a.name.localeCompare(b.name))
             })
         },
```
Comment (sbishel) [inline webapp/src/store/sidebar.ts:75]: Should only sort once.
```suggestion
            })
            // sort categories alphabetically
            state.categoryAttributes.sort((a, b) => a.name.localeCompare(b.name))
        },
```

**Review by sbishel — CHANGES_REQUESTED** [review]

File: webapp/src/store/sidebar.ts (hunk 1 above)
Comment (harshilsharma63) [reply webapp/src/store/sidebar.ts]: Done.

**Review by Pinjasaur — APPROVED** [review]
LGTM

**Review by sbishel — APPROVED** [review]
