### PR TITLE
Global template fetch fix

### LINKED ISSUE #1237: Bug: Predefined templates are missing
**Steps to reproduce the behavior:**
1. Go to Boards
2. Click on _Add board_
3. Observe the empty templates list

**Expected behavior:**
All the predefined templates should be listed

**Screenshots:**
templates

**Edition and Platform:**
Plugin v0.9.0 RC12 on community

 - Edition: Mattermost plugin
 - Version: v0.9.0 RC12
 - Browser and OS: Chrome 93 on Windows

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Fixed issue where global templates are not displayed.

#### Ticket Link
Fixes #1237

### CODE REVIEW

File: webapp/src/testUtils.tsx [hunk 1]
```diff
@@ -23,3 +23,19 @@ export function mockDOM(): void {
...
+    // This is required to provide it's definition since
+    // window.matchMedia doesn't exist in Jest.
+    Object.defineProperty(window, 'matchMedia', {
+        writable: true,
+        value: jest.fn().mockImplementation(() => {
+            return result
+
+            // return ({
+            //     matches: true,
+            // })
```
Comment (sbishel) [inline webapp/src/testUtils.tsx:38]: nit - remove commented lines.

**Review by sbishel — APPROVED** [review]

**Comment by sbishel** [comment]
Brought down and tested, templates now display.

File: webapp/src/testUtils.tsx (hunk 1 above)
Comment (sbishel) [reply webapp/src/testUtils.tsx:38]:
```suggestion
            
```
