### PR TITLE
Prevented workspace switcher from settiong dashboard as the last visited workspace

### LINKED ISSUE #1597: Bug: Desktop app > Refresh removes all items from the sidebar
## Steps to reproduce the behavior

1. Go to Boards dashboard on the desktop app
2. Refresh (CMD/CTRL+R)
3. Observe that the sidebar is now blank and the center view shows the "Create a board" screen

## Expected behavior

User should land on the dashboard.

## Screenshots

desktop_refresh

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.9.2; latest main
 - Browser and OS: Desktop app v5.0 on Windows

### PR DESCRIPTION
**Pull request by harshilsharma63**
#### Summary
Prevented workspace switcher from setting dashboard as the last visited workspace

#### Ticket Link
Fixes #1597

### CODE REVIEW

File: webapp/src/components/workspaceSwitcher/workspaceSwitcher.tsx [hunk 1]
```diff
@@ -62,9 +62,8 @@ const WorkspaceSwitcher = (props: Props): JSX.Element => {
                             newPath = '/dashboard'
                         } else {
                             newPath = `/workspace/${workspaceId}`
+                            UserSettings.lastWorkspaceId = workspaceId
                         }
```
Comment (hahmadia) [inline webapp/src/components/workspaceSwitcher/workspaceSwitcher.tsx:66]: I saw the original bug ticket. You can make this change so that after a CTRL+R you still land on the dashboard.
```suggestion
                            newPath = '/dashboard'
                            UserSettings.lastWorkspaceId = null
                        } else {
                            newPath = `/workspace/${workspaceId}`
                            UserSettings.lastWorkspaceId = workspaceId
                        }
```
I tried it locally and it worked on the desktop app. You can try it out and report if you have the same result.
Thanks

**Review by hahmadia — CHANGES_REQUESTED** [review]
A minor change to resolve showing dashboard after refresh

File: webapp/src/components/workspaceSwitcher/workspaceSwitcher.tsx (hunk 1 above)
Comment (harshilsharma63) [reply webapp/src/components/workspaceSwitcher/workspaceSwitcher.tsx:66]: It works only when you don't have the last board and view ID in local storage. Can we address this separately to avoid delaying this issue?

Comment (hahmadia) [reply webapp/src/components/workspaceSwitcher/workspaceSwitcher.tsx:66]: @harshilsharma63 

Why couldn't we set those to null? Does that cause some other issues?

**Review by hahmadia — APPROVED** [review]
Spoke about this offline. We will have it this way for now and create a new ticket to reload the dashboard properly. Thanks Harshil

**Comment by harshilsharma63** [comment]
@ogi-m can you try this out before I cherrypick for 0.10?

**Comment by ogi-m** [comment]
@harshilsharma63 I completely missed this - trying this now from latest main just opens a blank page on refresh

dashboard_desktopjpg

**Comment by harshilsharma63** [comment]
@ogi-m this is even happening in the `release-0.10` branch. I'm looking into it.
